import { SUI_TYPE_ARG } from '@mysten/sui.js';

import { OBJECT_RECORD, SUI_DEV_NET_CHAIN, SUI_TEST_NET_CHAIN } from './index';

export const DEV_NET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  BNB: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::BNB`,
  ETH: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::ETH`,
  BTC: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::BTC`,
  USDT: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::USDT`,
  USDC: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::USDC`,
  DAI: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::coins::DAI`,
  IPX: `${OBJECT_RECORD[SUI_DEV_NET_CHAIN].PACKAGE_ID}::ipx::IPX`,
};

export const TESTNET_NET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  BNB: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::BNB`,
  ETH: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::ETH`,
  BTC: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::BTC`,
  USDT: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::USDT`,
  USDC: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::USDC`,
  DAI: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::coins::DAI`,
  IPX: `${OBJECT_RECORD[SUI_TEST_NET_CHAIN].PACKAGE_ID}::ipx::IPX`,
};

export const COINS = {
  [SUI_DEV_NET_CHAIN]: DEV_NET_BASE_COINS,
  [SUI_TEST_NET_CHAIN]: DEV_NET_BASE_COINS,
};

export const DEX_BASE_TOKEN_ARRAY = {
  [SUI_DEV_NET_CHAIN]: [DEV_NET_BASE_COINS.ETH],
  [SUI_TEST_NET_CHAIN]: [TESTNET_NET_BASE_COINS.ETH],
};
